//Teste de Requisições REST
@baseURL = http://localhost:4000

###
// GET - Lista todas os veículos
GET {{baseURL}}/veiculos
Content-Type: application/json

###
// POST - Inclui um novo veículo
POST {{baseURL}}/veiculos
Content-Type: application/json

{
    "marca":"Fiat",
    "modelo":"Palio",
    "ano": 2001,
    "placa":"EOK8130",
    "status":"ativo"
}