//Teste de Requisições REST
@baseURL = http://localhost:4000
@id = 615b7fdd752fa2753b2f7966

###
// GET - Lista todas os veículos
GET {{baseURL}}/veiculos
Content-Type: application/json

###
// GET - Lista um único veículo pelo ID
GET {{baseURL}}/veiculos/{{id}}
Content-Type: application/json

###
// POST - Inclui um novo veículo
POST {{baseURL}}/veiculos
Content-Type: application/json

{
    "marca":"Renault",
    "modelo":"Duster",
    "ano": 2014,
    "placa":"JEG2P309",
    "cor":"Marrom",
    "status":"ativo"
}

###
// PUT - Altera dados de um veículo existente
PUT {{baseURL}}/veiculos
Content-Type: application/json

{
    "_id":"61550f3e541f83c81d8f7ce5",
    "marca":"Nissan",
    "modelo":"Kicks",
    "ano": 2020,
    "placa":"KEW2328",
    "cor":"Amarelo",
    "status":"ativo"
}

###
// DELETE - Exclui um veículo pelo ID
DELETE {{baseURL}}/veiculos/{{id}}
Content-Type: application/json