//Teste de Requisições REST
@baseURL = http://localhost:4000
@id = 6154842cd0fc70134fae8f03

###
// GET - Lista todas os veículos
GET {{baseURL}}/veiculos
Content-Type: application/json

###
// GET - Lista todas os veículos
GET {{baseURL}}/veiculos/{{id}}
Content-Type: application/json

###
// POST - Inclui um novo veículo
POST {{baseURL}}/veiculos
Content-Type: application/json

{
    "marca":"Nissan",
    "modelo":"Kicks",
    "ano": 2020,
    "placa":"KEW2328",
    "cor":"Vermelho",
    "status":"ativo"
}

###
// PUT - Altera dados de um veículo existente
PUT {{baseURL}}/veiculos
Content-Type: application/json

{
    "_id":"61550f3e541f83c81d8f7ce5",
    "marca":"Nissan",
    "modelo":"Kicks",
    "ano": 2020,
    "placa":"KEW2328",
    "cor":"Cinza/Laranja",
    "status":"ativo"
}

###
// DELETE - Exclui um veículo pelo ID
DELETE {{baseURL}}/veiculos/{{id}}
Content-Type: application/json